version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: nextauth
      MYSQL_USER: user
      MYSQL_PASSWORD: password1234
    ports:
      - "3306:3306"
    volumes:
      - next-auth-db-data:/var/lib/mysql
    networks:
      - bridge

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # volumes:
    #   - /path/to/config:/config
    ports:
      - 3005:3000
      - 3006:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - next-auth-db

networks:
  next-auth-db:
    external: false
    # name: bridge

volumes:
  next-auth-db-data: